# Generated by Django 4.2.5 on 2026-01-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stuapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="student",
            new_name="Stuapp",
        ),
    ]
